apiVersion: apps/v1 
kind: Deployment
metadata:
  name: comeandeat
spec:
  selector:
    matchLabels:
      app: comeandeat
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: comeandeat
        tier: frontend
    spec:
      containers:
      - name: comeandeat
        image: docker.io/rodion31/comeandeat:latest
        env:
        - name: primer
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8080
