apiVersion: v1
kind: Service
metadata:
  labels:
    app: comeandeatmysql
    tier: db
  name: comeandeatmysql
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: comeandeatmysql
    tier: db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
